[common]
synced_files = []

[[profiles]]
name = "Personal"
synced_files = [
    ".config/doom",
    ".config/fish",
    ".config/foot",
    ".config/fuzzel",
    ".config/helix",
    ".config/hypr",
    ".config/kanata",
    ".config/keyd",
    ".config/kglobalshortcutsrc",
    ".config/kitty",
    ".config/mako",
    ".config/niri",
    ".config/nvim",
    ".config/opencode",
    ".config/quickshell",
    ".config/rofi",
    ".config/starship.toml",
    ".config/tmux",
    ".config/waybar",
    ".config/wezterm",
    ".config/wofi",
    ".config/zed",
]
packages = []
